INSERT INTO PERMISSION VALUES(1, 'VIEW');
INSERT INTO PERMISSION VALUES(2, 'SEARCH');
INSERT INTO PERMISSION VALUES(3, 'ADD');
INSERT INTO PERMISSION VALUES(4, 'DELETE');

INSERT INTO USERS VALUES (1, 'userA', 'userA', true, 'firstnameA', 'lastnameA', 'user.a@domain.com');
INSERT INTO USER_PERM VALUES (1, 1);
INSERT INTO USER_PERM VALUES (1, 2);
INSERT INTO USERS VALUES (2, 'userB', 'userB', true, 'firstnameB', 'lastnameB', 'user.b@domain.com');
INSERT INTO USER_PERM VALUES (2, 1);
INSERT INTO USER_PERM VALUES (2, 2);
INSERT INTO USER_PERM VALUES (2, 3);
INSERT INTO USER_PERM VALUES (2, 4);

INSERT INTO CATEGORY VALUES (1, 'Dogs');
INSERT INTO CATEGORY VALUES (2, 'Cats');
INSERT INTO CATEGORY VALUES (3, 'Lions');
INSERT INTO CATEGORY VALUES (4, 'Horses');
INSERT INTO CATEGORY VALUES (5, 'Rabbits');

INSERT INTO TAG VALUES (1, 'Baby');
INSERT INTO TAG VALUES (2, 'Old');
INSERT INTO TAG VALUES (3, 'Long hair');
INSERT INTO TAG VALUES (4, 'Short hair');
INSERT INTO TAG VALUES (5, 'Captured');
INSERT INTO TAG VALUES (6, 'Native');

INSERT INTO PET VALUES (1, 'Dog 1', 'available'); INSERT INTO PET_CATEGORY VALUES (1, 1); INSERT INTO PET_TAG VALUES (1, 1);
INSERT INTO PET VALUES (2, 'Dog 2', 'available'); INSERT INTO PET_CATEGORY VALUES (2, 1); INSERT INTO PET_TAG VALUES (2, 6);
INSERT INTO PET VALUES (3, 'Dog 3', 'sold'); INSERT INTO PET_CATEGORY VALUES (3, 1); INSERT INTO PET_TAG VALUES (3, 3);
INSERT INTO PET VALUES (4, 'Dog 4', 'sold'); INSERT INTO PET_CATEGORY VALUES (4, 1);
INSERT INTO PET VALUES (5, 'Dog 5', 'available'); INSERT INTO PET_CATEGORY VALUES (5, 1);

INSERT INTO PHOTO_URL VALUES (1, 'http://lorempixel.com/182/200/animals/', 1);
INSERT INTO PHOTO_URL VALUES (2, 'http://lorempixel.com/182/200/animals/', 2);
INSERT INTO PHOTO_URL VALUES (3, 'http://lorempixel.com/182/200/animals/', 3);
INSERT INTO PHOTO_URL VALUES (4, 'http://lorempixel.com/182/200/animals/', 4);
INSERT INTO PHOTO_URL VALUES (5, 'http://lorempixel.com/182/200/animals/', 5);

INSERT INTO PET VALUES (6, 'Cat 1', 'sold'); INSERT INTO PET_CATEGORY VALUES (6, 2); INSERT INTO PET_TAG VALUES (6, 2);
INSERT INTO PET VALUES (7, 'Cat 2', 'available'); INSERT INTO PET_CATEGORY VALUES (7, 2); INSERT INTO PET_TAG VALUES (7, 6);
INSERT INTO PET VALUES (8, 'Cat 3', 'sold'); INSERT INTO PET_CATEGORY VALUES (8, 2);
INSERT INTO PET VALUES (9, 'Cat 4', 'sold'); INSERT INTO PET_CATEGORY VALUES (9, 2);
INSERT INTO PET VALUES (10, 'Cat 5', 'available'); INSERT INTO PET_CATEGORY VALUES (10, 2); INSERT INTO PET_TAG VALUES (10, 4);
INSERT INTO PET VALUES (11, 'Cat 6', 'pending'); INSERT INTO PET_CATEGORY VALUES (11, 2);
INSERT INTO PET VALUES (12, 'Cat 7', 'available'); INSERT INTO PET_CATEGORY VALUES (12, 2);

INSERT INTO PHOTO_URL VALUES (6, 'http://lorempixel.com/182/200/animals/', 6);
INSERT INTO PHOTO_URL VALUES (7, 'http://lorempixel.com/182/200/animals/', 7);
INSERT INTO PHOTO_URL VALUES (8, 'http://lorempixel.com/182/200/animals/', 8);
INSERT INTO PHOTO_URL VALUES (9, 'http://lorempixel.com/182/200/animals/', 9);
INSERT INTO PHOTO_URL VALUES (10, 'http://lorempixel.com/182/200/animals/', 10);
INSERT INTO PHOTO_URL VALUES (11, 'http://lorempixel.com/182/200/animals/', 11);
INSERT INTO PHOTO_URL VALUES (12, 'http://lorempixel.com/182/200/animals/', 12);

INSERT INTO PET VALUES (13, 'Lion 1', 'available'); INSERT INTO PET_CATEGORY VALUES (13, 3); INSERT INTO PET_TAG VALUES (13, 6);
INSERT INTO PET VALUES (14, 'Lion 2', 'available'); INSERT INTO PET_CATEGORY VALUES (14, 3); INSERT INTO PET_TAG VALUES (14, 6);
INSERT INTO PET VALUES (15, 'Lion 3', 'pending'); INSERT INTO PET_CATEGORY VALUES (15, 3); INSERT INTO PET_TAG VALUES (15, 6);

INSERT INTO PHOTO_URL VALUES (13, 'http://lorempixel.com/182/200/animals/', 13);
INSERT INTO PHOTO_URL VALUES (14, 'http://lorempixel.com/182/200/animals/', 14);
INSERT INTO PHOTO_URL VALUES (15, 'http://lorempixel.com/182/200/animals/', 15);

INSERT INTO PET VALUES (16, 'Horse 1', 'available'); INSERT INTO PET_CATEGORY VALUES (16, 4); INSERT INTO PET_TAG VALUES (16, 1);
INSERT INTO PET VALUES (17, 'Horse 2', 'available'); INSERT INTO PET_CATEGORY VALUES (16, 4);

INSERT INTO PHOTO_URL VALUES (16, 'http://lorempixel.com/182/200/animals/', 16);
INSERT INTO PHOTO_URL VALUES (17, 'http://lorempixel.com/182/200/animals/', 17);

INSERT INTO PET VALUES (18, 'Rabbit 1', 'available'); INSERT INTO PET_CATEGORY VALUES (18, 5);
INSERT INTO PET VALUES (19, 'Rabbit 2', 'available'); INSERT INTO PET_CATEGORY VALUES (19, 5); INSERT INTO PET_TAG VALUES (19, 3);
INSERT INTO PET VALUES (20, 'Rabbit 3', 'pending'); INSERT INTO PET_CATEGORY VALUES (20, 5); INSERT INTO PET_TAG VALUES (20, 4);
INSERT INTO PET VALUES (21, 'Rabbit 4', 'sold'); INSERT INTO PET_CATEGORY VALUES (21, 5);

INSERT INTO PHOTO_URL VALUES (18, 'http://lorempixel.com/182/200/animals/', 18);
INSERT INTO PHOTO_URL VALUES (19, 'http://lorempixel.com/182/200/animals/', 19);
INSERT INTO PHOTO_URL VALUES (20, 'http://lorempixel.com/182/200/animals/', 20);
INSERT INTO PHOTO_URL VALUES (21, 'http://lorempixel.com/182/200/animals/', 21);